import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  pythonSidebar: [{type: 'autogenerated', dirName: 'python'}],
  markdownSidebar: [{type: 'autogenerated', dirName: 'markdown'}],
};

export default sidebars;
